### ISSUE TITLE
[BUG]table of contents out of place

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#147] opened 2022-12-09 14:48 UTC
did something broke? I don't remember seeing this outside of the main grid

link to https://melodious-puffpuff-8e1109.netlify.app/docs/fundamentals/peer-to-peer

![Screen Shot 2022-12-09 02 46 42 PM](https://user-images.githubusercontent.com/1120748/206727950-e2edfbcc-0f2a-49c8-8bf8-065fa844e1ee.png)

screenshot in Safari

**Comment by minimalsm** [comment] 2022-12-09 15:13
This is not closed by #146.

It's caused by span overflow on the code block. 

1. Go to: https://melodious-puffpuff-8e1109.netlify.app/docs/getting-started/consensus-clients
2. Inspect code block and see span overflowing
3. Delete first code block and see bug disappears

![Screenshot 2022-12-09 at 15 10 55](https://user-images.githubusercontent.com/62268199/206733288-174ab9aa-c194-457f-b09c-b9758ec1c89b.png)

**Closed** 2022-12-13 13:23 UTC
