### ISSUE TITLE
[UI] - FAQ spacing on mobile

### ISSUE THREAD

**Issue by pettinarip** [ethereum/geth-website#100] opened 2022-12-01 14:08 UTC
The FAQ page seems to have different spacing sizes between the title and the content.

FAQ
![image](https://user-images.githubusercontent.com/468158/205072897-744bfa12-dcff-467a-887a-36ef61511ff0.png)

Other doc page
![image](https://user-images.githubusercontent.com/468158/205073465-e160be89-5396-4e6e-ba00-0b31fb997238.png)

**Comment by minimalsm** [comment] 2022-12-01 15:14
[Also present here, for example](https://melodious-puffpuff-8e1109.netlify.app/docs/fundamentals/security).

The space difference is caused by a lack of content between H1 and H2. 

margin bottom of H1 container + the margin top of H2 **versus** margin bottom of paragraph + margin top of H2

**Comment by corwintines** [comment] 2022-12-07 02:20
This was addressed in https://github.com/ethereum/geth-website/pull/109, going to close.

**Closed by corwintines** 2022-12-07 02:20 UTC
